version: '3'
services:
  backend:
    build: 
    - context: ./backend
    - dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: backend
  frontend:
    build: 
    - context: ./frontend
    - dockerfile: Dockerfile
    ports:
      - 5173:5173
    container_name: frontend